// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping/{ip}/{params}": {
            "get": {
                "description": "Send an ICMP ping request to a specified IP address and retrieve results, including latency if requested.",
                "tags": [
                    "Ping"
                ],
                "summary": "ICMP Ping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target IP Address",
                        "name": "ip",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Ping parameters in the format: {count}/{timeout}. Default count is 5, and default timeout is 3600 seconds.",
                        "name": "params",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "Specify 'yes' to include latency data in the response.",
                        "name": "get_latency",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Response with ping result and latency data (if requested)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Ping API 文档",
	Description:      "一个用于执行 ping 命令的示例 API。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
